apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracker-argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoogleKelompok/deploy.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: tracker-argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
